on:
  schedule:
    - cron:  '35 2 * * 6'
    
  workflow_dispatch:

name: generate-translations

jobs:
  generate-translations:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.REPO_KEY }}
      WEBLATE_KEY: ${{ secrets.WEBLATE_KEY }}
      QML_REPO: jaspanova-qml
      R_REPO: jaspanova-r
      
    steps:
      - uses: jasp-stats/jasp-actions/wlcLock@master
      
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_KEY }}

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.2.1"

      - uses: jasp-stats/jasp-actions/translations@master

